### ISSUE TITLE
brutespray erroring out

### ISSUE THREAD

**Issue by gbiagomba** [x90skysn3k/brutespray#44]
I noticed the below err when tried running the script on my Mac. I tried both with `~/` and calling the file explicitly. I still get the same error. This is the system I am running on `Darwin HQSML-1689616 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64`

```
 python3 /opt/brutespray/brutespray.py --file YJ-2020Q3-nmap_portknock-2020.10.07-17.15.47.gnmap -U ~/path/to/file/usernames.list -P ~/path/to/file/passwords.list --threads 10 --hosts 10 -c --output ../l00tz

 brutespray.py v1.6.8
 Created by: Shane Young/@x90skysn3k && Jacob Robles/@shellfail
 Inspired by: Leon Johnson/@sho-luv
 Credit to Medusa: JoMo-Kun / Foofus Networks <jmk@foofus.net>

Starting to brute, please make sure to use the right amount of threads(-t) and parallel hosts(-T)...
Output will be written to the folder: ./../l00tz/ \

Brute-Forcing...
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/brutespray/brutespray.py", line 245, in brute
    if args.userlist is None and args.username is None:
NameError: name 'args' is not defined
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/brutespray/brutespray.py", line 245, in brute
    if args.userlist is None and args.username is None:
NameError: name 'args' is not defined
```

**Comment by x90skysn3k** [comment]
this has to do with the way MacOS handles multiprocessing, i pushed an update to the [testing-1.6.9](https://github.com/x90skysn3k/brutespray/tree/testing-1.6.9)

**Comment by gbiagomba** [comment]
Thank you! @x90skysn3k

**Comment by x90skysn3k** [comment]
no problem! closing issue
