### ISSUE TITLE
error in selecting services

### ISSUE THREAD

**Issue by eaulakh** [x90skysn3k/brutespray#48]
Command used:- python brutespray.py --file ~/recon//nmap/jio.gnmap -i --service ssh

Welcome to interactive mode!

WARNING: Leaving an option blank will leave it empty and refer to default

Available services to brute-force:
Service: ssh on port 22 with 2 hosts
Service: postgres on port 5432 with 3 hosts

Enter services you want to brute - default all (ssh,ftp,etc): ssh
Traceback (most recent call last):
  File "brutespray.py", line 424, in <module>
    interactive()
  File "brutespray.py", line 90, in interactive
    args.service = input('\n' + colors.lightblue + 'Enter services you want to brute - default all (ssh,ftp,etc): ' + colors.red)
  File "<string>", line 1, in <module>
NameError: name 'ssh' is not defined

System type: ubuntu 18

**Comment by c-f** [comment]
Hi, 
i would assume you used python2.7 and not python3. 

It should work if you use 
```bash
python3 brutespray.py --file ~/recon//nmap/jio.gnmap -i --service ssh
```

The reason is that the `input` function works differently if both python versions. If you use python2 `input` also evalues your input. Since no **ssh** variable is defined an error is thrown. 

- https://docs.python.org/2.7/library/functions.html#input
- https://docs.python.org/3/library/functions.html#input
